name: run-tests
on:
  push:
    branches:
      - ci-setup
jobs:
  linear_tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: test_run
        run: |
          echo 'Running tests'
          echo pwd
          python setup.py install
          python stk/ops/linear_ops_tests.py
