name: run-tests
on: [push]
jobs:
  linear_tests:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: test_run
        run: |
          echo 'Setup...'
          python setup.py install --prefix ~/.local
          echo 'Uninstall Triton-2.0.0...'
          pip uninstall -y triton
          echo 'Install Triton-2.1.0...'
          cd third_party/triton/python
          pip install -e .
          echo 'Run tests...'
          python stk/ops/linear_ops_tests.py
