name: run-tests
on: [push]
jobs:
  linear_tests:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: test_run
        run: |
          echo 'Running tests'
          sudo python setup.py install
          python stk/ops/linear_ops_tests.py
